# docker-compose.yml for demo-cyverse-ag

version: '2'

services:
  cyverse_irods_dev:
    image: cyverse-irods-dev
    build:
      context: .
      dockerfile: Dockerfile.new
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    privileged: true
